=== FelixBronnhuber/RenderBaby/src/data_plane/scene_io/scene_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "required": [
        "scene_name",
        "objects",
        "background_color",
        "camera",
        "lights"
    ],
    "additionalProperties": false,
    "properties": {
        "scene_name": {
            "type": "string",
            "minLength": 0
        },
        "objects": {
            "type": "array",
            "minItems": 0,
            "items": {
                "$ref": "#/$defs/object"
            }
        },
        "background_color": {
            "$ref": "#/$defs/color"
        },
        "camera": {
            "$ref": "#/$defs/camera"
        },
        "lights": {
            "type": "array",
            "minItems": 0,
            "items": {
                "$ref": "#/$defs/light"
            }
        },
        "spheres": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/sphere"
            }
        },
        "ray_samples": {
            "type": "number"
        },
        "hash_color": {
            "type": "boolean"
        }
    },
    "$defs": {
        "vec3": {
            "type": "object",
            "required": [
                "x",
                "y",
                "z"
            ],
            "additionalProperties": false,
            "properties": {
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                },
                "z": {
                    "type": "number"
                }
            }
        },
        "color": {
            "type": "object",
            "required": [
                "r",
                "g",
                "b"
            ],
            "additionalProperties": {
                "a": {
                    "type": "number",
                    "minimum": 0.0,
                    "maximum": 1.0
                }
            },
            "properties": {
                "r": {
                    "type": "number",
                    "minimum": 0.0,
                    "maximum": 1.0
                },
                "g": {
                    "type": "number",
                    "minimum": 0.0,
                    "maximum": 1.0
                },
                "b": {
                    "type": "number",
                    "minimum": 0.0,
                    "maximum": 1.0
                }
            }
        },
        "object": {
            "type": "object",
            "required": [
                "name",
                "path",
                "scale",
                "rotation",
                "translation"
            ],
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "scale": {
                    "$ref": "#/$defs/vec3"
                },
                "rotation": {
                    "$ref": "#/$defs/vec3"
                },
                "translation": {
                    "$ref": "#/$defs/vec3"
                }
            }
        },
        "camera": {
            "type": "object",
            "required": [
                "position",
                "look_at",
                "up",
                "pane_distance",
                "pane_width",
                "resolution"
            ],
            "additionalProperties": false,
            "properties": {
                "position": {
                    "$ref": "#/$defs/vec3"
                },
                "look_at": {
                    "$ref": "#/$defs/vec3"
                },
                "up": {
                    "$ref": "#/$defs/vec3"
                },
                "pane_distance": {
                    "type": "number",
                    "exclusiveMinimum": 0
                },
                "pane_width": {
                    "type": "number",
                    "exclusiveMinimum": 0
                },
                "resolution": {
                    "type": "object",
                    "required": [
                        "x",
                        "y"
                    ],
                    "additionalProperties": false,
                    "properties": {
                        "x": {
                            "type": "integer",
                            "minimum": 1
                        },
                        "y": {
                            "type": "integer",
                            "minimum": 1
                        }
                    }
                }
            }
        },
        "light": {
            "type": "object",
            "required": [
                "name",
                "type",
                "luminosity",
                "position",
                "color"
            ],
            "additionalProperties": {
                "rotation": {
                    "$ref": "#/$defs/vec3"
                }
            },
            "properties": {
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "ambient",
                        "point",
                        "directional"
                    ]
                },
                "luminosity": {
                    "type": "number",
                    "exclusiveMinimum": 0
                },
                "position": {
                    "$ref": "#/$defs/vec3"
                },
                "color": {
                    "$ref": "#/$defs/color"
                }
            }
        },
        "sphere": {
            "type": "object",
            "required": [
                "center",
                "radius",
                "material",
                "color",
                "name",
                "scale",
                "translation",
                "rotation"
            ],
            "properties": {
                "center": {
                    "$ref": "#/$defs/vec3"
                },
                "radius": {
                    "type": "number"
                },
                "material": {
                    "$ref": "#/$defs/sphereMaterial"
                },
                "color": {
                    "$ref": "#/$defs/color"
                },
                "name": {
                    "type": "string"
                },
                "scale": {
                    "$ref": "#/$defs/vec3"
                },
                "translation": {
                    "$ref": "#/$defs/vec3"
                },
                "rotation": {
                    "$ref": "#/$defs/vec3"
                }
            },
            "additionalProperties": false
        },
        "sphereMaterial": {
            "type": "object",
            "required": [
                "name",
                "ambient_reflectivity",
                "diffuse_reflectivity",
                "specular_reflectivity",
                "emissive",
                "shininess",
                "transparency"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "ambient_reflectivity": {
                    "type": "array",
                    "items": { "type": "number" }
                },
                "diffuse_reflectivity": {
                    "type": "array",
                    "items": { "type": "number" }
                },
                "specular_reflectivity": {
                    "type": "array",
                    "items": { "type": "number" }
                },
                "emissive": {
                    "type": "array",
                    "items": { "type": "number" }
                },
                "shininess": {
                    "type": "number"
                },
                "transparency": {
                    "type": "number"
                }
            },
            "additionalProperties": false
        }
    }
}

=== FelixBronnhuber/RenderBaby/templates/scene/sphere.json
{
  "scene_name": "scene",
  "objects": [],
  "lights": [
    {
      "name": "proto_light",
      "type": "ambient",
      "position": {
        "x": 0.0,
        "y": 0.0,
        "z": 3.0
      },
      "luminosity": 0.0,
      "color": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "rotation": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      }
    },
    {
      "name": "point_light",
      "type": "point",
      "position": {
        "x": 2.0,
        "y": 4.0,
        "z": 1.0
      },
      "luminosity": 20.0,
      "color": {
        "r": 1.0,
        "g": 0.9,
        "b": 0.8
      },
      "rotation": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      }
    }
  ],
  "camera": {
    "position": {
      "x": 5.0,
      "y": 5.0,
      "z": 5.0
    },
    "look_at": {
      "x": 1.0,
      "y": 1.0,
      "z": 1.0
    },
    "up": {
      "x": 0.0,
      "y": 1.0,
      "z": 0.0
    },
    "pane_distance": 35.0,
    "pane_width": 36.0,
    "resolution": {
      "x": 1920,
      "y": 1080
    }
  },
  "background_color": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  }
}

=== FelixBronnhuber/RenderBaby/fixtures/scenes/sample-cube/example_scene.json
{
    "scene_name": "example",
    "objects": [
        {
            "name": "cube",
            "path": "obj/cube_bare.obj",
            "scale": {
                "x": 1.0,
                "y": 1.0,
                "z": 1.0
            },
            "rotation": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
            },
            "translation": {
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
            }
        }
    ],
    "background_color": {
        "r": 0.0,
        "g": 0.0,
        "b": 0.0
    },
    "camera": {
        "position": {
            "x": 3.5,
            "y": 3.5,
            "z": 3.0
        },
        "look_at": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
        },
        "up": {
            "x": 5.0,
            "y": -10.0,
            "z": 0.0
        },
        "pane_distance": 50.0,
        "pane_width": 100.0,
        "resolution": {
            "x": 1920,
            "y": 1080
        }
    },
    "lights": [
        {
            "name": "light 1",
            "type": "point",
            "luminosity": 1000.0,
            "position": {
                "x": -2.0,
                "y": -7.0,
                "z": 6.0
            },
            "color": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
            }
        },
        {
            "name": "light 2",
            "type": "point",
            "luminosity": 300.0,
            "position": {
                "x": 7.8,
                "y": -3.0,
                "z": 5.0
            },
            "color": {
                "r": 1.0,
                "g": 0.06,
                "b": 0.08
            }
        },
        {
            "name": "light 3",
            "type": "point",
            "luminosity": 100.0,
            "position": {
                "x": 3.0,
                "y": 7.6,
                "z": 8.5
            },
            "color": {
                "r": 0.04,
                "g": 1.0,
                "b": 0.15
            }
        }
    ]
}

=== FelixBronnhuber/RenderBaby/fixtures/benchmark.json
{
  "scene_name": "scene",
  "objects": [
    {
      "name": "ferris3d_v1.0.obj",
      "path": "ferris_high_poly\\ferris3d_v1.0.obj",
      "scale": {
        "x": 1.0,
        "y": 1.0,
        "z": 1.0
      },
      "translation": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "rotation": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      }
    }
  ],
  "lights": [
    {
      "name": "Light",
      "type": "point",
      "position": {
        "x": 0.0,
        "y": 2.0,
        "z": 0.0
      },
      "luminosity": 100.0,
      "color": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "rotation": {
        "x": 0.0,
        "y": 0.0,
        "z": -1.0
      }
    }
  ],
  "camera": {
    "position": {
      "x": 0.0,
      "y": 2.0,
      "z": 3.0
    },
    "look_at": {
      "x": 0.0,
      "y": 1.2,
      "z": 1.0
    },
    "up": {
      "x": 0.0,
      "y": 1.0,
      "z": 0.0
    },
    "pane_distance": 35.0,
    "pane_width": 36.0,
    "resolution": {
      "x": 512,
      "y": 512
    }
  },
  "background_color": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  }
}
